services:
  glob:
    build: .
    image: glob
    volumes:
      - ./mnemosyne:/mnemosyne:z
    ports:
      - "3000:80"
    networks:
      - "mononetwork"


networks:
  mononetwork:
    external: true
